package verbes;

import java.util.HashMap;

import conjugaison.HashMapBuilder;

public final class VerbeType {
	private static HashMap<String, String> aller = HashMapBuilder.build("Indicatif_présent", "vais,vas,va,allons,allez,vont",
			"Indicatif_imparfait", "allais,allais,allit,allions,alliez,allaient", "Indicatif_passé_simple",
			"allai,allas,alla,allâmes,allâtes,allèrent", "Indicatif_futur_simple", "irai,iras,ira,irons,irez,iront",
			"Conditionnel_présent", "irais,irais,irait,irions,iriez,iraient", "Subjonctif_présent",
			"aille,ailles,aille,allions,alliez,aillent", "Subjonctif_imparfait",
			"allasse,allasses,allât,allassions,allassiez,allassent", "Impératif_présent", "va,allons,allez",
			"Participe_présent", "allant", "Participe_passé", "allé", "Infinitif_présent", "aller");
	private static HashMap<String, String> vetir = HashMapBuilder.build("Indicatif_présent",
			"vêts,vêts,vêt,vêtons,vêtez,vêtent", "Indicatif_imparfait", "vêtais,vêtais,vêtait,vêtions,vêtiez,vêtaient",
			"Indicatif_passé_simple", "vêtis,vêtis,vêtit,vêtîmes,vêtîtes,vêtirent", "Indicatif_futur_simple",
			"vêtirai,vêtiras,vêtira,vêtirons,vêtirez,vêtiront", "Conditionnel_présent",
			"vêtirais,vêtirais,vêtirait,vêtirions,vêtiriez,vêtiraient", "Subjonctif_présent",
			"vête,vêtes,vête,vêtions,vêtiez,vêtent", "Subjonctif_imparfait",
			"vêtisse,vêtisses,vêtît,vêtissions,vêtissiez,vêtissent", "Impératif_présent", "vêts,vêtons,vêtez",
			"Participe_présent", "vêtant", "Participe_passé", "vêtu", "Infinitif_présent", "vêtir");
	private static HashMap<String, String> cueillir = HashMapBuilder.build("Indicatif_présent",
			"cueille,cueilles,cueille,cueillons,cueillez,cueillent", "Indicatif_imparfait",
			"cueillais,cueillais,cueillait,cueillions,cueilliez,cueillaient", "Indicatif_passé_simple",
			"cueillis,cueillis,cueillit,cueillîmes,cueillîtes,cueillirent", "Indicatif_futur_simple",
			"cueillerai,cueilleras,cueillera,cueillerons,cueillerez,cueilleront", "Conditionnel_présent",
			"cueillerais,cueillerais,cueillerait,cueillerions,cueilleriez,cueilleraient", "Subjonctif_présent",
			"cueille,cueilles,cueille,cueillions,cueilliez,cueillent", "Subjonctif_imparfait",
			"cueillisse,cueillisses,cueillît,cueillissions,cueillissiez,cueillissent", "Impératif_présent",
			"cueille,cueillons,cueillez", "Participe_présent", "cueillant", "Participe_passé", "cueilli",
			"Infinitif_présent", "cueillir");
	private static HashMap<String, String> faillir = HashMapBuilder.build("Indicatif_présent",
			"faux,faux,faut,faillons,faillez,faillent", "Indicatif_imparfait",
			"faillais,fallais,faillait,faillions,falliez,falillaient", "Indicatif_passé_simple",
			"faillis,faillis,faillit,faillîmes,faillîtes,faillirent", "Indicatif_futur_simple",
			"faillirai,failliras,faillira,faillirons,faillirez,failliront", "Conditionnel_présent",
			"faillirais,faillirais,faillirait,faillirions,failliriez,failliraient", "Subjonctif_présent",
			"faillisse,faillisses,faillisse,faillissions,faillissiez,faillissent", "Subjonctif_imparfait",
			"faillisse,faillisses,faillît,faillissions,faillissiez,faillissent", "Impératif_présent", "-,-,-",
			"Participe_présent", "faillant", "Participe_passé", "failli", "Infinitif_présent", "faillir");
	private static HashMap<String, String> bouillir = HashMapBuilder.build("Indicatif_présent",
			"bous,bous,bout,bouillons,bouillez,,bouillent", "Indicatif_imparfait",
			"bouillais,bouillais,bouillait,bouillions,bouilliez,bouillaient", "Indicatif_passé_simple",
			"bouillis,bouillis,bouillit,bouillîmes,bouillîtes,bouillirent", "Indicatif_futur_simple",
			"bouillirai,bouilliras,bouillira,bouillirons,bouillirez,bouilliront", "Conditionnel_présent",
			"bouillirais,bouillirais,bouillira,bouillirions,bouilliriez,bouilliraient", "Subjonctif_présent",
			"bouille,bouilles,bouille,bouillions,bouilliez,bouillent", "Subjonctif_imparfait",
			"bouillisse,bouillisses,bouillît,bouillissions,bouillissiez,bouillissent", "Impératif_présent",
			"bous,bouillons,bouillez", "Participe_présent", "bouillant", "Participe_passé", "bouilli",
			"Infinitif_présent", "bouillir");
	private static HashMap<String, String> dormir = HashMapBuilder.build("Indicatif_présent",
			"dors,dors,dort,dormons,dormez,dorment", "Indicatif_imparfait",
			"dormais,dormais,dormait,dormions,dormiez,dormaient", "Indicatif_passé_simple",
			"dormis,dormis,dormit,dormîmes,dormîtes,dormirent", "Indicatif_futur_simple",
			"dormirai,dormiras,dormira,dormirons,dormirez,dormiront", "Conditionnel_présent",
			"dormirais,dormirais,dormirait,dormirions,dormiriez,dormiraient", "Subjonctif_présent",
			"dorme,dormes,dorme,dormions,dormiez,dorment", "Subjonctif_imparfait",
			"dormisse,dormisses,dormît,dormissions,dormissiez,dormissent", "Impératif_présent", "dors,dormons,dormez",
			"Participe_présent", "dormant", "Participe_passé", "dormi", "Infinitif_présent", "dormir");
	private static HashMap<String, String> courir = HashMapBuilder.build("Indicatif_présent",
			"cours,cours,court,courons,courez,courent", "Indicatif_imparfait",
			"courais,courais,courait,courions,couriez,couraient", "Indicatif_passé_simple",
			"courus,courus,courut,courûmes,courûtes,coururent", "Indicatif_futur_simple",
			"courrai,courras,courra,courrons,courrez,courront", "Conditionnel_présent",
			"courrais,courrais,courrait,courrions,courriez,courraient", "Subjonctif_présent",
			"coure,coures,coure,courions,couriez,courent", "Subjonctif_imparfait",
			"courusse,courusses,courût,courussions,courussiez,courussent", "Impératif_présent", "cours,courons,courez",
			"Participe_présent", "courant", "Participe_passé", "couru", "Infinitif_présent", "courir");
	private static HashMap<String, String> mourir = HashMapBuilder.build("Indicatif_présent",
			"meurs,meurs,meurt,mourons,mourez,meurent", "Indicatif_imparfait",
			"mourais,mourais,mourait,mourions,mouriez,mouraient", "Indicatif_passé_simple",
			"mourus,mourus,mourut,mourûmes,mourûtes,moururent", "Indicatif_futur_simple",
			"mourrai,mourras,mourra,mourrons,mourrez,mourront", "Conditionnel_présent",
			"mourrais,mourrais,mourrait,mourrions,mourriez,mourraient", "Subjonctif_présent",
			"meure,meures,meure,mourions,mouriez,meurent", "Subjonctif_imparfait",
			"mourusse,mourusses,mourût,mourussions,mourussiez,mourussent", "Impératif_présent", "meurs,mourons,mourez",
			"Participe_présent", "mourant", "Participe_passé", "mort", "Infinitif_présent", "mourir");
	private static HashMap<String, String> servir = HashMapBuilder.build("Indicatif_présent",
			"sers,sers,sert,servons,servez,servent", "Indicatif_imparfait",
			"servais,servais,servait,servions,serviez,servaient", "Indicatif_passé_simple",
			"servis,servis,servit,servîmes,servîtes,servirent", "Indicatif_futur_simple",
			"servirai,serviras,servira,servirons,servirez,serviront", "Conditionnel_présent",
			"servirais,servirais,servirait,servirions,serviriez,serviraient", "Subjonctif_présent",
			"serve,serves,serve,servions,serviez,servent", "Subjonctif_imparfait",
			"servisse,servisses,servît,servissions,servissiez,servissent", "Impératif_présent", "sers,servons,servez",
			"Participe_présent", "servant", "Participe_passé", "servi", "Infinitif_présent", "servir");
	private static HashMap<String,String> fuir = HashMapBuilder.build(
			"Indicatif_présent", "fuis,fuis,fuit,fuyons,fuyez,fuient", "Indicatif_imparfait",
			"fuyais,fuyais,fuyait,fuyions,fuyiez,fuyaient", "Indicatif_passé_simple",
			"fuis,fuis,fuit,fuîmes,fuîtes,fuirent", "Indicatif_futur_simple",
			"fuirai,fuiras,fuira,fuirons,fuirez,fuiront", "Conditionnel_présent",
			"fuirais,fuirais,fuirait,fuirions,fuiriez,fuiraient", "Subjonctif_présent",
			"fuie,fuies,fuie,fuyions,fuyiez,fuient", "Subjonctif_imparfait",
			"fuisse,fuisses,fuît,fuissions,fuissiez,fuissent", "Impératif_présent", "fuis,fuyons,fuyez",
			"Participe_présent", "fuyant", "Participe_passé", "fui", "Infinitif_présent", "fuir");
	private static HashMap<String, String> ouir = HashMapBuilder.build("Indicatif_présent",
			"ois,ois,oit,oyons,oyez,oient", "Indicatif_imparfait", "oyais,oyais,oyait,oyions,oyiez,oyaient",
			"Indicatif_passé_simple", "ouïs,ouïs,ouït,ouïmes,ouïtes,ouïrent", "Indicatif_futur_simple",
			"ouïrai,ouIras,ouïra,ouïrons,ouïrez,ouïront", "Conditionnel_présent",
			"ouïrais,ouïrais,ouïrait,ouïrions,ouïriez,ouïraient", "Subjonctif_présent",
			"oie,oies,oie,oyions,oyiez,oient", "Subjonctif_imparfait",
			"ouïsse,ouïsses,ouït,ouïssions,ouïssiez,ouïssent", "Impératif_présent", "ois,oyons,oyez",
			"Participe_présent", "oyant", "Participe_passé", "ouï", "Infinitif_présent", "ouïr");
	private static HashMap<String, String> gesir = HashMapBuilder.build("Indicatif_présent",
			"gis,gis,gît,gisons,gisez,gisent", "Indicatif_imparfait", "gisais,gisais,gisait,gisions,gisiez,gisaient",
			"Indicatif_passé_simple", "-,-,-,-,-,-", "Indicatif_futur_simple", "-,-,-,-,-,-", "Conditionnel_présent",
			"-,-,-,-,-,-", "Subjonctif_présent", "-,-,-,-,-,-", "Subjonctif_imparfait", "-,-,-,-,-,-",
			"Impératif_présent", "-,-,-,", "Participe_présent", "gisant", "Participe_passé", "-", "Infinitif_présent",
			"gésir");
	private static HashMap<String, String> pourvoir = HashMapBuilder.build("Indicatif_présent",
			"pourvois,pourvois,pourvoit,pourvoyons,pourvoyez,pourvoient", "Indicatif_imparfait",
			"pourvoyais,pourvoyais,pourvoyait,pourvoyions,pourvoyiez,pourvoyaient", "Indicatif_passé_simple",
			"pourvus,pourvus,pourvut,pourvûmes,pourvûtes,pourvurent", "Indicatif_futur_simple",
			"pourvoirai,pourvoiras,pourvoira,pourvoirons,pourvoirez,pourvoiront", "Conditionnel_présent",
			"pourvoirais,pourvoirais,pourvoirait,pourvoirions,pourvoiriez,pourvoiraient", "Subjonctif_présent",
			"pourvoie,pourvoies,pourvoie,pourvoyions,pourvoyiez,pourvoient", "Subjonctif_imparfait",
			"pourvusse,pourvusses,pourvût,pourvussions,pourvussiez,pourvussent", "Impératif_présent",
			"pourvois,pourvoyons,pourvoyez", "Participe_présent", "pourvoyant", "Participe_passé", "pourvu",
			"Infinitif_présent", "pourvoir");
	private static HashMap<String, String> savoir = HashMapBuilder.build("Indicatif_présent",
			"sais,sais,sait,savons,savez,savent", "Indicatif_imparfait", "savais,savais,savait,savions,saviez,savaient",
			"Indicatif_passé_simple", "sus,sus,sut,sûmes,sûtes,surent", "Indicatif_futur_simple",
			"saurai,sauras,saura,saurons,saurez,sauront", "Conditionnel_présent",
			"saurais,saurais,saurait,saurions,sauriez,sauraient", "Subjonctif_présent",
			"sache,saches,sache,sachions,sachiez,sachent", "Subjonctif_imparfait",
			"susse,susses,sût,sussions,sussiez,sussent", "Impératif_présent", "sache,sachons,sachez",
			"Participe_présent", "sachant", "Participe_passé", "su", "Infinitif_présent", "savoir");
	private static HashMap<String, String> devoir = HashMapBuilder.build("Indicatif_présent",
			"dois,dois,doit,devons,devez,doivent", "Indicatif_imparfait",
			"devais,devais,devait,devions,deviez,devaient", "Indicatif_passé_simple", "dus,dus,dut,dûmes,dûtes,durent",
			"Indicatif_futur_simple", "devrai,devras,devra,devrons,devrez,devront", "Conditionnel_présent",
			"devrais,devrais,devrait,devrions,devriez,devraient", "Subjonctif_présent",
			"doive,doives,doive,devions,deviez,doivent", "Subjonctif_imparfait",
			"dusse,dusses,dût,dussions,dussiez,dussent", "Impératif_présent", "dois,devons,devez", "Participe_présent",
			"devant", "Participe_passé", "dû", "Infinitif_présent", "devoir");
	private static HashMap<String, String> pouvoir = HashMapBuilder.build("Indicatif_présent",
			"peux,peux,peut,pouvons,pouvez,peuvent", "Indicatif_imparfait",
			"pouvais,pouvais,pouvait,pouvions,pouviez,pouvaient", "Indicatif_passé_simple",
			"pus,pus,pus,put,pûmes,pûtes,purent", "Indicatif_futur_simple",
			"pourrai,pourras,pourra,pourrons,pourrez,pourront", "Conditionnel_présent",
			"pourrais,pourrais,pourrait,pourrions,pourriez,pourraient", "Subjonctif_présent",
			"puisse,puisses,puisse,puissions,puissiez,puissent", "Subjonctif_imparfait",
			"pusse,pusses,pût,pussions,pussiez,pussent", "Impératif_présent", "-,-,-", "Participe_présent", "pouvant",
			"Participe_passé", "pu", "Infinitif_présent", "pouvoir");
	private static HashMap<String, String> mouvoir = HashMapBuilder.build("Indicatif_présent",
			"meus,meus,meut,mouvons,mouvez,meuvent", "Indicatif_imparfait",
			"mouvais,mouvais,mouvait,mouvions,mouviez,mouvaient", "Indicatif_passé_simple",
			"mus,mus,mut,mûrent,mûtes,murent", "Indicatif_futur_simple",
			"mouvrai,mouvras,mouvra,mouvrons,mouvrez,mouvront", "Conditionnel_présent",
			"mouvrais,mouvrais,mouvrait,mouvrions,mouvriez,mouvraient", "Subjonctif_présent",
			"meuve,meuves,meuve,mouvions,mouviez,meuvent", "Subjonctif_imparfait",
			"musse,musses,mût,mussions,mussiez,mussent", "Impératif_présent", "meus,mouvons,mouvez",
			"Participe_présent", "mouvant", "Participe_passé", "mû", "Infinitif_présent", "mouvoir");
	private static HashMap<String, String> pleuvoir = HashMapBuilder.build("Indicatif_présent", "-,-,pleut,-,-,-",
			"Indicatif_imparfait", "-,-,pleuvait,-,-,-", "Indicatif_passé_simple", "-,-,plut,-,-,-",
			"Indicatif_futur_simple", "-,-,pleuvra,-,-,-", "Conditionnel_présent", "-,-,pleuvrait,-,-,-",
			"Subjonctif_présent", "-,-,pleuve,-,-,-", "Subjonctif_imparfait", "-,-,plût,-,-,-", "Impératif_présent",
			"-,-,-", "Participe_présent", "pleuvant", "Participe_passé", "plu", "Infinitif_présent", "pleuvoir");
	private static HashMap<String, String> voir = HashMapBuilder.build("Indicatif_présent",
			"vois,vois,voit,voyons,voyez,voient", "Indicatif_imparfait", "voyais,voyais,voyait,voyions,voyiez,voyaient",
			"Indicatif_passé_simple", "vis,vis,vit,vîmes,vîtes,virent", "Indicatif_futur_simple",
			"verrai,verras,verra,verrons,verrez,verront", "Conditionnel_présent",
			"verrais,verrais,verrait,verrions,verriez,verraient", "Subjonctif_présent",
			"voie,voies,voie,voyions,voyiez,voient", "Subjonctif_imparfait",
			"visse,visses,vît,vissions,vissiez,vissent", "Impératif_présent", "vois,voyons,voyez", "Participe_présent",
			"voyant", "Participe_passé", "vu", "Infinitif_présent", "voir");
	private static HashMap<String, String> falloir = HashMapBuilder.build("Indicatif_présent", "-,-,faut,-,-,-",
			"Indicatif_imparfait", "-,-,fallait,-,-,-", "Indicatif_passé_simple", "-,-,fallut,-,-,-",
			"Indicatif_futur_simple", "-,-,faudra,-,-,-", "Conditionnel_présent", "-,-,faudrait,-,-,-",
			"Subjonctif_présent", "-,-,faille,-,-,-", "Subjonctif_imparfait", "-,-,fallût,-,-,-", "Impératif_présent",
			"-,-,-", "Participe_présent", "-", "Participe_passé", "fallu", "Infinitif_présent", "falloir");
	private static HashMap<String, String> valoir = HashMapBuilder.build("Indicatif_présent",
			"vaux,vaux,vaut,valons,valez,valent", "Indicatif_imparfait", "valais,valais,valit,valions,valiez,valaient",
			"Indicatif_passé_simple", "valus,valus,valut,valûmes,valûtes,valurent", "Indicatif_futur_simple",
			"vaudrai,vaudras,vaudra,vaudrons,voudrez,vaudront", "Conditionnel_présent",
			"vaudrais,vaudrais,vaudrait,vaudrions,voudriez,vaudraient", "Subjonctif_présent",
			"vaille,vailles,vaille,valions,valiez,vaillent", "Subjonctif_imparfait",
			"valusse,valusses,valût,valussions,valussiez,valussent", "Impératif_présent", "vaux,valons,valez",
			"Participe_présent", "valant", "Participe_passé", "valu", "Infinitif_présent", "valoir");
	private static HashMap<String, String> vouloir = HashMapBuilder.build("Indicatif_présent",
			"veux,veux,veut,voulons,voulez,veulent", "Indicatif_imparfait",
			"voulais,voulais,voulait,voulions,vouliez,voulaient", "Indicatif_passé_simple",
			"voulus,voulus,voulut,voulûmes,voulûtes,voulurent", "Indicatif_futur_simple",
			"voudrai,voudras,voudra,voudrons,voudrez,voudront", "Conditionnel_présent",
			"voudrais,voudrais,voudrait,voudrions,voudriez,voudraient", "Subjonctif_présent",
			"veuille,veuilles,veuilles,voulions,vouliez,veuillent", "Subjonctif_imparfait",
			"voulusse,voulusses,voulût,voulussions,voulussiez,voulussent", "Impératif_présent",
			"veux/veuille,voulons,voulez/veuillez", "Participe_présent", "voulant", "Participe_passé", "voulu",
			"Infinitif_présent", "vouloir");
	private static HashMap<String, String> asseoir = HashMapBuilder.build("Indicatif_présent",
			"assieds/assois,assieds/assois/assied/assoit,asseyons/assoyons,asseyez/assoyez,asseyent/assoient",
			"Indicatif_imparfait",
			"asseyais/assoyais,asseyais/assoyais,asseyait/assoyait,asseyions/assoyions,asseyiez/assoyiez,asseyaient/assoyaient",
			"Indicatif_passé_simple", "assis,assis,assit,assîmes,assîtes,assirent", "Indicatif_futur_simple",
			"assiérai/assoirai,assiéras/assoiras,assiéra/assoira,assiérons/assoirons,assiérez/assoirez,assiéront/assoiront",
			"Conditionnel_présent",
			"assiérais/assoirais,assiérais/assoirais,assiérait/assoirait,assiérions/assoirions,assiériez/assoiriez,assiéraient/assoiraient",
			"Subjonctif_présent",
			"asseye/assoie,asseyes/assoies,asseye/assoie,asseyions/assoyions,asseyiez/assoyiez,asseyent/assoient",
			"Subjonctif_imparfait", "assisse,assisses,assît,assissions,assissiez,assissent", "Impératif_présent",
			"assieds/assois,asseyons/assoyons,asseyez/assoyez", "Participe_présent", "asseyant/assoyant",
			"Participe_passé", "assis", "Infinitif_présent", "asseoir");
	private static HashMap<String, String> messeoir = HashMapBuilder.build("Indicatif_présent",
			"-,-,messied,-,-,messiéent", "Indicatif_imparfait", "-,-,messeyait,-,-,messeyaient",
			"Indicatif_passé_simple", "-,-,-,-,-,-", "Indicatif_futur_simple", "-,-,messiéra,-,-,messiéront",
			"Conditionnel_présent", "-,-,messiérait,-,-,messiéraient", "Subjonctif_présent",
			"-,-,messiée,-,-,messiéent", "Subjonctif_imparfait", "-,-,-,-,-,-", "Impératif_présent", "-,-,-",
			"Participe_présent", "messéant", "Participe_passé", "-", "Infinitif_présent", "messeoir");
	private static HashMap<String, String> surseoir = HashMapBuilder.build("Indicatif_présent",
			"sursois,sursois,sursoit,sursoyons,sursoyez,sursoient", "Indicatif_imparfait",
			"sursoyais,sursoyais,sursoyait,sursoyions,sursoyiez,sursoyaient", "Indicatif_passé_simple",
			"sursis,sursis,sursit,sursîmes,surîtes,sursirent", "Indicatif_futur_simple",
			"surseoirai,surseoiras,surseoira,surseoirons,surseoirez,surseoiront", "Conditionnel_présent",
			"surseoirais,surseoirais,surseoirait,surseoirions,surseoiriez,surseoiraient", "Subjonctif_présent",
			"sursoie,sursoies,sursoie,sursoyions,sursoyiez,sursoient", "Subjonctif_imparfait",
			"sursisse,sursisses,sursît,sursissions,sursissiez,sursissent", "Impératif_présent",
			"sursois,sursoyons,suroyez", "Participe_présent", "sursoyant", "Participe_passé", "sursis",
			"Infinitif_présent", "surseoir");
	private static HashMap<String, String> seoir = HashMapBuilder.build("Indicatif_présent", "-,-,sied,-,-,-",
			"Indicatif_imparfait", "-,-,seyait,-,-,-", "Indicatif_passé_simple", "-,-,siéra,-,-,-",
			"Indicatif_futur_simple", "-,-,siéra,-,-,-", "Conditionnel_présent", "-,-,siérait,-,-,-",
			"Subjonctif_présent", "-,-,siée,-,-,-", "Subjonctif_imparfait", "-,-,-,-,-,-", "Impératif_présent", "-,-,-",
			"Participe_présent", "séant/seyant", "Participe_passé", "sis", "Infinitif_présent", "seoir");
	private static HashMap<String, String> echoir = HashMapBuilder.build("Indicatif_présent", "-,-,échoit,-,-,échoient",
			"Indicatif_imparfait", "-,-,échoyait,-,-,échoyaient", "Indicatif_passé_simple", "-,-,échut,-,-,échurent",
			"Indicatif_futur_simple", "-,-,échoira,-,-,échoirent", "Conditionnel_présent",
			"-,-,échoirait,-,-,échoiraient", "Subjonctif_présent", "-,-,échoie,-,-,échoient", "Subjonctif_imparfait",
			"-,-,échût,-,-,échussent", "Impératif_présent", "-,-,-", "Participe_présent", "échéant", "Participe_passé",
			"échu", "Infinitif_présent", "échoir");
	private static HashMap<String, String> dechoir = HashMapBuilder.build("Indicatif_présent",
			"déchois,déchois,déchoit,déchoyons,déchoyez,déchoient", "Indicatif_imparfait", "-,-,-,-,-,-",
			"Indicatif_passé_simple", "déchus,déchus,déchut,déchûmes,déchûtes,décurent", "Indicatif_futur_simple",
			"déchoirai,déchoiras,déchoira,déchoirons,déchoirez,déchoiront", "Conditionnel_présent",
			"déchoirais,déchoirais,déchoirait,déchoirions,déchoiriez,déchoiraient", "Subjonctif_présent",
			"déchoie,déchoies,déchoie,déchoyions,déchoyiez,déchoient", "Subjonctif_imparfait",
			"déchusse,déchusses,déchût,déchussions,déchussiez,déchussent", "Impératif_présent", "-,-,-",
			"Participe_présent", "-", "Participe_passé", "déchu", "Infinitif_présent", "déchoir");
	private static HashMap<String, String> choir = HashMapBuilder.build("Indicatif_présent",
			"chois,chois,choit,choyons,choyez,choient", "Indicatif_imparfait", "-,-,-,-,-,-", "Indicatif_passé_simple",
			"chus,chus,chut,cûmes,chûtes,churent", "Indicatif_futur_simple",
			"choirai,choiras,choira,choirons,choirez,choiront", "Conditionnel_présent",
			"choirais,choirais,choirait,choirions,choiriez,choiraient", "Subjonctif_présent", "-,-,-,-,-,-",
			"Subjonctif_imparfait", "-,-,chût,-,-,-", "Impératif_présent", "-,-,-", "Participe_présent", "-",
			"Participe_passé", "chu", "Infinitif_présent", "choir");
	private static HashMap<String,String> rompre = HashMapBuilder.build(
			"Indicatif_présent",
			"",
			"Indicatif_imparfait",
			"",
			"Indicatif_passé_simple",
			"",
			"Indicatif_futur_simple",
			"",
			"Conditionnel_présent",
			"",
			"Subjonctif_présent",
			"",
			"Subjonctif_imparfait",
			"",
			"Impératif_présent",
			"",
			"Participe_présent",
			"",
			"Participe_passé",
			"",
			"Infinitif_présent",
			""
			);
	private static HashMap<String, String> prendre = HashMapBuilder.build("Indicatif_présent",
			"prends,prends,prend,prenons,prenez,prennent", "Indicatif_imparfait",
			"prenais,prenais,prenait,prenions,preniez,prenaient", "Indicatif_passé_simple",
			"pris,pris,prit,prîmes,prîtes,prirent", "Indicatif_futur_simple",
			"prendrai,prendras,prendra,prendrons,prendrez,prendront", "Conditionnel_présent",
			"prendrais,prendrais,prendrait,prendrions,prendriez,prendraient", "Subjonctif_présent",
			"prenne,prennes,prenne,prenions,preniez,prennent", "Subjonctif_imparfait",
			"prisse,prisses,prît,prissions,prissiez,prissent", "Impératif_présent", "prends,prenons,prenez",
			"Participe_présent", "prenant", "Participe_passé", "pris", "Infinitif_présent", "prendre");
	private static HashMap<String, String> battre = HashMapBuilder.build("Indicatif_présent",
			"bats,bats,bat,battons,battez,battent", "Indicatif_imparfait",
			"battais,battais,battait,battions,battiez,battaient", "Indicatif_passé_simple",
			"battis,battis,battit,battîmes,battîtes,battirent", "Indicatif_futur_simple",
			"battrai,battras,battra,battrons,battrez,battront", "Conditionnel_présent",
			"battrais,battrais,battrait,battrions,battriez,battraient", "Subjonctif_présent",
			"batte,battes,batte,battions,battiez,battent", "Subjonctif_imparfait",
			"battisse,batisses,battît,battissions,battissiez,battissent", "Impératif_présent", "bats,battons,battez",
			"Participe_présent", "battant", "Participe_passé", "battu", "Infinitif_présent", "battre");
	private static HashMap<String, String> mettre = HashMapBuilder.build("Indicatif_présent",
			"mets,mets,met,mettons,mettez,mettent", "Indicatif_imparfait",
			"mettais,mettais,mettait,mettions,mettiez,mettaient", "Indicatif_passé_simple",
			"mis,mis,mit,mîmes,mîtes,mirent", "Indicatif_futur_simple",
			"mettrai,mettras,mettra,mettrons,mettrez,mettront", "Conditionnel_présent",
			"mettrais,mettrais,mettrait,mettrions,mettriez,mettraient", "Subjonctif_présent",
			"mette,mettes,mette,mettions,mettiez,mettent", "Subjonctif_imparfait",
			"misse,misses,mît,missions,missiez,missent", "Impératif_présent", "mets,mettons,mettez",
			"Participe_présent", "mettant", "Participe_passé", "mis", "Infinitif_présent", "mettre");
	private static HashMap<String, String> vaincre = HashMapBuilder.build("Indicatif_présent",
			"vaincs,vaincs,vainc,vainquons,vainquez,vaiquent", "Indicatif_imparfait",
			"vainquais,vainquais,vainquait,vainquions,vainquiez,vainquaient", "Indicatif_passé_simple",
			"vainquis,vainquis,vainquit,vainquîmes,vainquîtes,vainquirent", "Indicatif_futur_simple",
			"vaincrai,vaincras,vaincra,vaincrons,vaincrez,vaincront", "Conditionnel_présent",
			"vaincrais,vaincrais,vaincrait,vaincrions,vaincriez,vaincraient", "Subjonctif_présent",
			"vainque,vainques,vainque,vainquions,vainquiez,vainquent", "Subjonctif_imparfait",
			"vainquisse,vainquisses,vainquît,vainquissions,vainquissiez,vainquissent", "Impératif_présent",
			"vaincs,vainquons,vainquez", "Participe_présent", "vainquant", "Participe_passé", "vaincu",
			"Infinitif_présent", "vaincre");
	private static HashMap<String, String> faire = HashMapBuilder.build("Indicatif_présent",
			"fais,fais,fait,faisons,faites,font", "Indicatif_imparfait",
			"faisais,faisais,faisait,faisions,faisiez,faissaient", "Indicatif_passé_simple",
			"fis,fis,fit,fîmes,fîtes,firent", "Indicatif_futur_simple", "ferai,feras,fera,ferons,ferez,feront",
			"Conditionnel_présent", "ferais,ferais,ferait,ferions,feriez,feraient", "Subjonctif_présent",
			"fasse,fasses,fasse,fassions,fassiez,fassent", "Subjonctif_imparfait",
			"fisse,fisses,fît,fissions,fissiez,fissent", "Impératif_présent", "fais,faisons,faites",
			"Participe_présent", "faisant", "Participe_passé", "fait", "Infinitif_présent", "faire");
	private static HashMap<String, String> plaire = HashMapBuilder.build("Indicatif_présent",
			"plais,plais,plaît,plaisonsplaisez,plaisent", "Indicatif_imparfait",
			"plaisais,plaisais,plaisait,plaisions,plaisiez,plaisaient", "Indicatif_passé_simple",
			"plus,plus,plut,plûmes,plûtes,plurent", "Indicatif_futur_simple",
			"plairai,plairas,plaira,plairons,plairez,plairont", "Conditionnel_présent",
			"plairais,plairais,plairait,plairions,plairiez,plairaient", "Subjonctif_présent",
			"plaise,plaises,plaise,plaisions,plaisiez,plaisent", "Subjonctif_imparfait",
			"plusse,plusses,plût,plussions,plussiez,plussent", "Impératif_présent", "plais,plaisons,plaisez",
			"Participe_présent", "plaisant", "Participe_passé", "plu", "Infinitif_présent", "plaire");
	private static HashMap<String, String> taire = HashMapBuilder.build("Indicatif_présent",
			"tais,tais,tait,taisons,taisez,taisent", "Indicatif_imparfait",
			"taisais,taisais,taisait,taissions,taisiez,taisaient", "Indicatif_passé_simple",
			"tus,tus,tut,tûmes,tûtes,turent", "Indicatif_futur_simple", "tairai,tairas,taira,tairons,tairez,tairont",
			"Conditionnel_présent", "tairais,tairais,tairait,tairions,tairiez,tairaient", "Subjonctif_présent",
			"taise,taises,taise,taissions,taissiez,taisent", "Subjonctif_imparfait",
			"tusse,tusses,tût,tussions,tussiez,tussent", "Impératif_présent", "tais,taisons,taisez",
			"Participe_présent", "taisant", "Participe_passé", "tû", "Infinitif_présent", "taire");
	private static HashMap<String, String> naitre = HashMapBuilder.build("Indicatif_présent",
			"nais,nais,naît,naissons,naissez,naissent", "Indicatif_imparfait",
			"naissais,naissais,naissait,naissions,naissiez,naissaient", "Indicatif_passé_simple",
			"naquis,naquis,naquit,naquîmes,naquîtes,naquirent", "Indicatif_futur_simple",
			"naîtrai,naîtras,naîtra,naîtrons,naîtrez,naîtront", "Conditionnel_présent",
			"naîtrais,naîtrais,naîtrait,naîtrions,naîtriez,naîtraient", "Subjonctif_présent",
			"naisse,naisses,naisse,naissions,naissiez,naissent", "Subjonctif_imparfait",
			"naquisse,naquisses,naquît,naqissions,naquissiez,naquissent", "Impératif_présent", "nais,naissons,naissee",
			"Participe_présent", "naissant", "Participe_passé", "né", "Infinitif_présent", "naître");
	private static HashMap<String, String> repaitre = HashMapBuilder.build("Indicatif_présent",
			"repais,repais,repaît,repaissons,repaissez,repaissent", "Indicatif_imparfait",
			"repaissais,repaissais,repaissait,repaissions,repaissiez,repaissaient", "Indicatif_passé_simple",
			"repus,repus,reput,repûmes,repûtes,repurent", "Indicatif_futur_simple",
			"repaîtrai,repaîtras,repaîtra,repaîtrons,repaîtrez,repaîtront", "Conditionnel_présent",
			"repaîtrais,repaîtrais,repaîtrait,repaîtrions,repaîtriez,repaîtraient", "Subjonctif_présent",
			"repaisse,repaisses,repaisse,repaissions,repaissiez,repaissent", "Subjonctif_imparfait",
			"repusse,repusses,repût,repussions,repussiez,repussent", "Impératif_présent", "repais,repaissons,repaissez",
			"Participe_présent", "repaissant", "Participe_passé", "repu", "Infinitif_présent", "repaître");
	private static HashMap<String, String> paitre = HashMapBuilder.build("Indicatif_présent",
			"pais,pais,paît,paissons,paissez,paissent", "Indicatif_imparfait",
			"paissais,paissais,paissait,paissions,paissiez,paissaient", "Indicatif_passé_simple", "-,-,-,-,-,-",
			"Indicatif_futur_simple", "paîtrai,paîtras,paîtra,paîtrons,paîtz,paîtront", "Conditionnel_présent",
			"paîtrais,paîtrais,paîtrait,paîtrions,paîtriez,paîtraient", "Subjonctif_présent",
			"paisse,paisses,paisse,paissions,paissiez,paissent", "Subjonctif_imparfait", "-,-,-,-,-,-",
			"Impératif_présent", "repais,paissons,paissez", "Participe_présent", "paissant", "Participe_passé", "-",
			"Infinitif_présent", "paître");
	private static HashMap<String, String> croitre = HashMapBuilder.build("Indicatif_présent",
			"crois,crois,croît,croissons,croissez,croissent", "Indicatif_imparfait",
			"croissais,croissais,croissait,croissions,croissiez,croissaient", "Indicatif_passé_simple",
			"crûs,crûs,crût,crûmes,crûtes,crûrent", "Indicatif_futur_simple",
			"croîtrai,croîtras,croîtra,croîtrons,croîtrez,croîtront", "Conditionnel_présent",
			"croîtrais,croîtrais,croîtrait,croîtrions,croîtriez,croîtraient", "Subjonctif_présent",
			"croisse,croisses,croisse,croissions,croissiez,croissent", "Subjonctif_imparfait",
			"crûsse,crûsses,crût,crûssions,crûssiez,crûssent", "Impératif_présent", "crois,croissons,croissez",
			"Participe_présent", "croissant", "Participe_passé", "crû", "Infinitif_présent", "croître");
	private static HashMap<String, String> croire = HashMapBuilder.build("Indicatif_présent",
			"crois,crois,croit,croyons,croyez,croient", "Indicatif_imparfait",
			"croyais,croyais,croyait,croyions,croyiez,croyaient", "Indicatif_passé_simple",
			"crus,crus,crut,crûmes,crûtes,crurent", "Indicatif_futur_simple",
			"croirai,croiras,croira,croirons,croirez,croiront", "Conditionnel_présent",
			"croirais,croirais,croirait,croirions,croiriez,croiraient", "Subjonctif_présent",
			"croie,croies,croie,croyions,croyiez,croient", "Subjonctif_imparfait",
			"crusse,crusses,crût,crussions,crussiez,crussent", "Impératif_présent", "crois,croyons,croyez",
			"Participe_présent", "croyant", "Participe_passé", "cru", "Infinitif_présent", "croire");
	private static HashMap<String, String> boire = HashMapBuilder.build("Indicatif_présent",
			"bois,bois,boit,buvons,buvez,boient", "Indicatif_imparfait", "buvais,buvais,buvait,buvions,buviez,buvaient",
			"Indicatif_passé_simple", "bus,bus,but,bûmes,bûtes,burent", "Indicatif_futur_simple",
			"boirai,boiras,boira,boirons,boirez,boiront", "Conditionnel_présent",
			"boirais,boirais,boirait,boirions,boiriez,boiraient", "Subjonctif_présent",
			"boive,boives,boive,buvions,buviez,boivent", "Subjonctif_imparfait",
			"busse,busses,bpût,bussions,bussiez,bussent", "Impératif_présent", "bois,buvons,buvez", "Participe_présent",
			"buvant", "Participe_passé", "bu", "Infinitif_présent", "boire");
	private static HashMap<String, String> clore = HashMapBuilder.build("Indicatif_présent",
			"clos,clos,clôt,-,-,closent", "Indicatif_imparfait", "-,-,-,-,-,-", "Indicatif_passé_simple", "-,-,-,-,-,-",
			"Indicatif_futur_simple", "clorai,cloras,clora,clorons,clorez,cloront", "Conditionnel_présent",
			"clorais,clorais,clorait,clorions,cloriez,cloraient", "Subjonctif_présent",
			"close,closes,close,closions,closiez,closent", "Subjonctif_imparfait", "-,-,-,-,-,-", "Impératif_présent",
			"clos,-,-", "Participe_présent", "closant", "Participe_passé", "clos", "Infinitif_présent", "clore");
	private static HashMap<String, String> resoudre = HashMapBuilder.build("Indicatif_présent",
			"résous,résous,résout,résolvons,résolvez,résolvent", "Indicatif_imparfait",
			"résolvais,résolvais,résolvait,résolvions,résolviez,résolvaient", "Indicatif_passé_simple",
			"résolus,résolus,résolut,résolûmes,résolûtes,résolurent", "Indicatif_futur_simple",
			"résoudrai,résoudras,résoudra,résoudrons,résoudrez,résoudront", "Conditionnel_présent",
			"résoudrais,résoudrais,résoudrait,résoudrions,résoudriez,résoudraient", "Subjonctif_présent",
			"résolve,résolves,résolve,résolvions,résolviez,résolvent", "Subjonctif_imparfait",
			"résolusse,résolusses,résolût,résolussions,résolussiez,résolussent", "Impératif_présent",
			"résous,résolvons,résolvez", "Participe_présent", "résolvant", "Participe_passé", "résolu",
			"Infinitif_présent", "résoudre");
	private static HashMap<String, String> coudre = HashMapBuilder.build("Indicatif_présent",
			"couds,couds,coud,cousons,cousez,cousent", "Indicatif_imparfait",
			"cousais,cousais,cousait,cousions,cousiez,cousaient", "Indicatif_passé_simple",
			"cousis,cousis,cousit,cousîmes,cousîtes,cousirent", "Indicatif_futur_simple",
			"coudrai,coudras,coudra,coudrons,coudrez,coudront", "Conditionnel_présent",
			"coudrais,coudrais,coudrait,coudrions,coudriez,coudraient", "Subjonctif_présent",
			"couse,couses,couse,cousions,cousiez,cousent", "Subjonctif_imparfait",
			"cousisse,cousisses,cousît,cousissions,cousissiez,cousissent", "Impératif_présent", "couds,cousons,cousez",
			"Participe_présent", "cousant", "Participe_passé", "cousu", "Infinitif_présent", "coudre");
	private static HashMap<String, String> moudre = HashMapBuilder.build("Indicatif_présent",
			"mouds,mouds,moud,moulons,moulez,moulent", "Indicatif_imparfait",
			"moulais,moulais,moulait,moulions,mouliez,moulaient", "Indicatif_passé_simple",
			"moulus,moulus,moulut,moulûmes,moulûtes,moulurent", "Indicatif_futur_simple",
			"moudrai,moudras,moudra,moudrez,moudront", "Conditionnel_présent",
			"moudrais,moudrais,moudrait,moudriez,moudraient", "Subjonctif_présent",
			"moule,moules,moule,moulions,mouliez,moulent", "Subjonctif_imparfait",
			"moulusse,moulusses,moulût,moulussions,moulussiez,moulussent", "Impératif_présent", "mouds,moulons,moulez",
			"Participe_présent", "moulant", "Participe_passé", "moulu", "Infinitif_présent", "moudre");
	private static HashMap<String, String> suivre = HashMapBuilder.build("Indicatif_présent",
			"suis,suis,suit,suivons,suivez,suivent", "Indicatif_imparfait",
			"suivais,suivais,suivait,suivions,suiviez,suivaient", "Indicatif_passé_simple",
			"suivis,suivis,suivit,suivîmes,suivîtes,suivirent", "Indicatif_futur_simple",
			"suivrai,suivras,suivra,suivrons,suivrez,suivront", "Conditionnel_présent",
			"suivrais,suivrais,suivrait,suivrions,suivriez,suivraient", "Subjonctif_présent",
			"suive,suives,suive,suivions,suiviez,suivent", "Subjonctif_imparfait",
			"suivisse,suivisses,suivît,suivissions,suivissiez,suivissent", "Impératif_présent", "suis,suivons,suivez",
			"Participe_présent", "suivant", "Participe_passé", "suivi", "Infinitif_présent", "suivre");
	private static HashMap<String, String> vivre = HashMapBuilder.build("Indicatif_présent",
			"vis,visvit,vivons,vivez,vivent", "Indicatif_imparfait", "vivais,viavais,vivait,vivions,viviez,vivaient",
			"Indicatif_passé_simple", "vécus,vécus,vécut,vécûmes,vécûtes,vécurent", "Indicatif_futur_simple",
			"vivrai,vivras,vivra,vivrons,vivrez,vivront", "Conditionnel_présent",
			"vivrais,vivrais,vivrait,vivrions,vivriez,vivraient", "Subjonctif_présent",
			"vive,vives,vive,vivions,viviez,vivent", "Subjonctif_imparfait",
			"vécusse,vécusses,vécût,vécussions,vécussiez,vécussent", "Impératif_présent", "vis,vivons,vivez",
			"Participe_présent", "vivant", "Participe_passé", "vécu", "Infinitif_présent", "vivre");
	private static HashMap<String, String> lire = HashMapBuilder.build("Indicatif_présent",
			"lis,lis,lit,lisons,lisez,lisent", "Indicatif_imparfait", "lisais,lisais,lisait,lisions,lisiez,lisaient",
			"Indicatif_passé_simple", "lus,lus,lut,lûmes,lûtes,lurent", "Indicatif_futur_simple",
			"lirai,liras,lira,lirons,lirez,liront", "Conditionnel_présent",
			"lirais,lirais,lirait,lirions,liriez,liraient", "Subjonctif_présent",
			"lise,lises,lise,lisions,lisiez,lisent", "Subjonctif_imparfait", "lusse,lusses,lû,lussions,lussiez,lussent",
			"Impératif_présent", "lis,lisons,lisez", "Participe_présent", "lisant", "Participe_passé", "lu",
			"Infinitif_présent", "lire");
	private static HashMap<String, String> dire = HashMapBuilder.build("Indicatif_présent",
			"dis,dis,dit,disons,disez,disent", "Indicatif_imparfait", "disais,disais,disait,disions,disiez,disaient",
			"Indicatif_passé_simple", "dis,dis,dit,dîmes,dîtes,dirent", "Indicatif_futur_simple",
			"dirai,diras,dira,dirons,direz,diront", "Conditionnel_présent",
			"dirais,dirais,dirait,dirions,diriez,diraient", "Subjonctif_présent",
			"dise,dises,dise,disions,disiez,disent", "Subjonctif_imparfait",
			"disse,disses,dît,dissions,dissiez,dissent", "Impératif_présent", "dis,disons,disez", "Participe_présent",
			"disant", "Participe_passé", "dit", "Infinitif_présent", "dire");
	private static HashMap<String, String> ecrire = HashMapBuilder.build("Indicatif_présent",
			"écris,écris,écrit,écrivons,écrivez,écrivent", "Indicatif_imparfait",
			"écrivais,écrivais,écrivait,écrivions,écriviez,écrivaient", "Indicatif_passé_simple",
			"écrivis,écrivis,écrivit,écrivîmes,écrivîtes,écrivirent", "Indicatif_futur_simple",
			"écrirai,écriras,écrira,écrirons,écrirez,écriront", "Conditionnel_présent",
			"écrirais,écrirais,écrirait,écririons,écririez,écriraient", "Subjonctif_présent",
			"écrive,écrives,écrive,écrivions,écriviez,écrivent", "Subjonctif_imparfait",
			"écrivisse,écrivisses,écrivît,écrivissions,écrivissiez,écrivissent", "Impératif_présent",
			"écris,écrivons,écrivez", "Participe_présent", "écrivant", "Participe_passé", "écrit", "Infinitif_présent",
			"écrire");
	private static HashMap<String, String> rire = HashMapBuilder.build("Indicatif_présent",
			"ris,ris,rit,rions,riez,rient", "Indicatif_imparfait", "riais,risais,riait,riions,riiez,riaient",
			"Indicatif_passé_simple", "ris,ris,rit,rîmes,rîtes,rirent", "Indicatif_futur_simple",
			"rirai,riras,rira,rirons,rirez,riront", "Conditionnel_présent",
			"rirais,rirais,rirait,ririons,ririez,riraient", "Subjonctif_présent", "rie,ries,rie,riions,riiez,rient",
			"Subjonctif_imparfait", "risse,risses,rît,rissions,rissiez,rissent", "Impératif_présent", "ris,rions,riez",
			"Participe_présent", "riant", "Participe_passé", "ri", "Infinitif_présent", "rire");
	private static HashMap<String, String> confire = HashMapBuilder.build("Indicatif_présent",
			"confis,confis,confit,confisons,confisez,confisent", "Indicatif_imparfait",
			"confisais,confisais,confisait,confisions,confisiez,confisaient", "Indicatif_passé_simple",
			"confis,confis,confit,confîmes,confîtes,confirent", "Indicatif_futur_simple",
			"confirai,confiras,confira,confirons,confirez,confiront", "Conditionnel_présent",
			"confirais,confirais,confirait,confirions,confiriez,confiraient", "Subjonctif_présent",
			"confise,confises,confise,confisions,confisiez,confisent", "Subjonctif_imparfait",
			"confisse,confisses,confît,confissions,confissiez,confissent", "Impératif_présent",
			"confis,confisons,confisez", "Participe_présent", "confisant", "Participe_passé", "confit",
			"Infinitif_présent", "confire");

	private static HashMap[] exceptions = { aller, vetir, cueillir, faillir, bouillir, dormir, courir, mourir,
			servir, fuir, ouir, gesir, pourvoir, savoir, devoir, pouvoir, mouvoir, pleuvoir, voir,
			falloir, valoir, vouloir, asseoir, messeoir, surseoir, seoir, echoir, dechoir, choir,
			rompre, prendre, battre, mettre, vaincre, faire, plaire, taire, naitre, repaitre,
			paitre, croitre, croire, boire, clore, resoudre, coudre, moudre, suivre, vivre, lire,
			dire, ecrire, rire, confire };

	private VerbeType(String v) {}

	public static HashMap<String,String> getAffixes(String v) {
		for (HashMap<String, String> hm : exceptions) {
			if (hm.get("Infinitif_présent").equals(v))
				return hm;
		}
		return null;
	}
}
